### ISSUE TITLE
MailGuardian Web GUI not working properly 

### ISSUE THREAD

**Issue by merlinnoman** [KHIT93/mailguardian#121]
**Describe the bug**
I have installed the MailGuardian using the installer.sh. The installation went successfully but as I was trying to access the web console I am getting error which mentions that : Uncaught SyntaxError: Cannot use import statement outside a module from app.js:1.upon investigation I found out that the issue is happening  on the file that is located under assests/src/js/app.js and the import modules were not working properly. As a result, I only see a spinning circle on the web page. 

**Screenshots**
If applicable, add screenshots to help explain your question to others.

**Application information**
 - MailGuardian version: [e.g. 1.5.3]
 - Python version: python3
 - PostgreSQL version: 13.10
 - Postfix version: 3.5.8
 - MailScanner version: 5.4

**Desktop (please complete the following information):**
 - OS: AlmaLinux
 - Browser: Chrome , Edge 
 - Version 112.0.5615.138

**Comment by KHIT93** [comment]
Thank you for reacing out.
Have not come across that specific error.
Currently debugging it to see where the issue could be

**Comment by KHIT93** [comment]
Hi
Seems that I got it resolved.
When logged in as `root`, the following should get you up and running again:

```
sudo su - mailguardian
cd mailguardian
rm -rf node_modules
git pull
npm install
npm run production
exit
sudo systemctl restart mailguardian
```

**Comment by merlinnoman** [comment]
Hi, I just followed your instruction and still getting the same error. I have attached a following ss of how it looks like in the web console: 
![image](https://user-images.githubusercontent.com/132305148/236848552-2827d57a-bf5d-4f6c-9a00-71d3e3e8c1a3.png)

Thanks again

**Comment by KHIT93** [comment]
I am not able to reproduce your issue on a fresh install.

If you have already tried to clear the caches of your browser without any luck, I need you to do it again after running the below commands:

```
sudo su - mailguardian
cd mailguardian
npm run dev
exit
sudo systemctl restart mailguardian
```

Then send me the screenshot from the browser console again so that it becomes easier to see where in the code that a potential error might be raised.
Also could you share with me if you are using AlmaLinux 8 or AlmaLinux 9?

**Comment by merlinnoman** [comment]
I am using AlmaLinux 8.7. From your end you do not see the error? I am wondering if I have missed anything during installation.

**Comment by merlinnoman** [comment]
I was able to resolve the issue and run the application. thanks so much. Amazing work!
