### ISSUE TITLE
Missing polyfill for IE11

### ISSUE THREAD

**Issue by kenneth-vkd** [KHIT93/mailguardian#25]
When opening the `MailGuardian` interface in `Internet Explorer 11`, you just see the background.
It complains in the debug console about methods related to `Promises` in `ES6`, so maybe a polyfill is missing.

It would be great to have either a polyfill for making the system work with `IE` or have a message show that `IE` is not supported.

**Comment by KHIT93** [comment]
What we will do is add an additional `script` tag and check if the browser supports the `ES6` features that we are using.
Using that we will be able to load in a `polyfill` for features that are normally not supported in a give browser
