### ISSUE TITLE
Domain level whitelisting / wildcard whitelisting is not working

### ISSUE THREAD

**Issue by kenneth-vkd** [KHIT93/mailguardian#26]
We have tried to add a whitelisting for *@domain1.com to *@domain2.dk
However, emails are still stopped as spam

**Comment by KHIT93** [comment]
These have to be added without *@domain.com
You should simply leave the `*` out and then it will work

**Comment by kenneth-vkd** [comment]
Hi
We have now tested further on the problem and it seems to be related to a problem with the API/UI
When a user selects the from as either email or IP and then do not set a to address, then it still saves.

This does effectively allow users to perform a full wildcard whitelisting/blacklisting
