### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by blackcobra1973** [KHIT93/mailguardian#29]
Hello,  

I am trying to install mail guardian, and during the process there are questions about database user/passwords etc..    But I not see any database created nor do I find any documentation about what I must create first already and empty database and user or not.  

Can you help me out ? 

Thanks in advance, 

Kurt

**Comment by KHIT93** [comment]
Hi
Thank you for your interest in this project.
You have to create the database username/password manually and you also have to make sure that the created user has access to the database, which you also need to create manually.
Currently we include instructions for how to add the PostgreSQL repo, as it will help getting a tested PostgreSQL version to use with the project.
We might add instructions for how to add the user and database to our instructions in the future.

For now, you can add the user using these commands:

```
sudo -u postgres psql
postgres=# create database mailguardian;
postgres=# create user mailguardian with encrypted password 'Sup3rSecr€tP@ssw0rd';
postgres=# grant all privileges on database mailguardian to mailguardian;
```

**Comment by blackcobra1973** [comment]
Thank you very much
