### ISSUE TITLE
[BUG] npm not checked for presence during install

### ISSUE THREAD

**Issue by shawniverson** [KHIT93/mailguardian#76]
**Describe the bug**
npm not installed prior to installation script causes mailguardian build to fail

**To Reproduce**
1. Install Debian 10 default no gui, standard system utilities
2. Run mailguardian install 

**Expected behavior**
Should check for npm prior to invoking and install it if missing

**Comment by KHIT93** [comment]
Thanks for reporting. Will look at it over the next few days

**Comment by KHIT93** [comment]
Currently testing a fix for this as it turns out to be a missing `curl` package, which is required for the installation method used for install `nodejs` and thereby alsl `npm`.

A fix will be available later today

**Comment by KHIT93** [comment]
This has now been fixed
Once again thanks for reporting the issue :)
