### ISSUE TITLE
Installation issue on Ubuntu 20.04.3

### ISSUE THREAD

**Issue by freyuh** [KHIT93/mailguardian#83]
Hello,

today I wanted to install mailguardian on a freshly installed Ubuntu 20.04.3 Server, but the installation script ended with an error:

Installing MailGuardian...
CREATE DATABASE
CREATE ROLE
GRANT
Traceback (most recent call last):
  File "./installer/mailguardian.py", line 66, in <module>
    installer_config['mailguardian']['secret'] = get_random_secret_key()
  File "/usr/lib/python3.8/configparser.py", line 1259, in __setitem__
    return self._parser.set(self._name, key, value)
  File "/usr/lib/python3.8/configparser.py", line 1201, in set
    super().set(section, option, value)
  File "/usr/lib/python3.8/configparser.py", line 894, in set
    value = self._interpolation.before_set(self, section, option,
  File "/usr/lib/python3.8/configparser.py", line 402, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in 'u%yq^p5xem!@m@71run2hmrd+9*n0###soj0oq9*83(=q#ih4j' at position 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./installer/mailguardian.py", line 68, in <module>
    installer_config['mailguardian']['secret'] = get_random_secret_key()
  File "/usr/lib/python3.8/configparser.py", line 1259, in __setitem__
    return self._parser.set(self._name, key, value)
  File "/usr/lib/python3.8/configparser.py", line 1201, in set
    super().set(section, option, value)
  File "/usr/lib/python3.8/configparser.py", line 894, in set
    value = self._interpolation.before_set(self, section, option,
  File "/usr/lib/python3.8/configparser.py", line 402, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in '6do3ae^8_%nyp=%-hwnosn+uk$321zfbs&w0zrc#c@xug=bb53' at position 9
We are really sorry, but something seems to have gone wrong or the script was aborted

And ClamAV can't be build:

Starting Build Compile Stage
  Starting "perl Makefile.PL" Stage
Unrecognized argument in LIBS ignored: '-clamav'
Generating a Unix-style Makefile
Writing Makefile for Mail::ClamAV
Writing MYMETA.yml and MYMETA.json
  Finished "perl Makefile.PL" Stage

  Starting "make" Stage
make[1]: Entering directory '/root/.cpan/build/Mail-ClamAV-0.30-0/_Inline/build/Mail/ClamAV'
Running Mkbootstrap for ClamAV ()
chmod 644 "ClamAV.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- ClamAV.bs blib/arch/auto/Mail/ClamAV/ClamAV.bs 644
"/usr/bin/perl" "/usr/share/perl/5.30/ExtUtils/xsubpp"  -typemap "/usr/share/perl/5.30/ExtUtils/typemap"   ClamAV.xs > ClamAV.xsc
mv ClamAV.xsc ClamAV.c
x86_64-linux-gnu-gcc -c  -iquote"/root/.cpan/build/Mail-ClamAV-0.30-0" -I/usr/include -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"0.30\" -DXS_VERSION=\"0.30\" -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.30/CORE"   ClamAV.c
ClamAV.xs: In function ‘clamav_perl_maxreclevel’:
ClamAV.xs:131:9: warning: ‘return’ with no value, in function returning non-void
  131 |         return;
      |         ^~~~~~
ClamAV.xs:115:5: note: declared here
  115 | int clamav_perl_maxreclevel(SV *self, ...)
      |     ^~~~~~~~~~~~~~~~~~~~~~~
ClamAV.xs: In function ‘clamav_perl_maxfiles’:
ClamAV.xs:158:9: warning: ‘return’ with no value, in function returning non-void
  158 |         return;
      |         ^~~~~~
ClamAV.xs:142:5: note: declared here
  142 | int clamav_perl_maxfiles(SV *self, ...)
      |     ^~~~~~~~~~~~~~~~~~~~
ClamAV.xs: In function ‘clamav_perl_maxfilesize’:
ClamAV.xs:179:9: warning: ‘return’ with no value, in function returning non-void
  179 |         return;
      |         ^~~~~~
ClamAV.xs:163:5: note: declared here
  163 | int clamav_perl_maxfilesize(SV *self, ...)
      |     ^~~~~~~~~~~~~~~~~~~~~~~
ClamAV.xs: In function ‘clamav_perl__scanfd’:
ClamAV.xs:219:30: warning: passing argument 2 of ‘cl_scandesc’ from incompatible pointer type [-Wincompatible-pointer-types]
  219 |     status = cl_scandesc(fd, &virname, &scanned, c->root, options);
      |                              ^~~~~~~~
      |                              |
      |                              const char **
In file included from ClamAV.xs:11:
/usr/include/clamav.h:894:53: note: expected ‘const char *’ but argument is of type ‘const char **’
  894 | extern cl_error_t cl_scandesc(int desc, const char *filename, const char **virname, unsigned long int *scanned, const struct cl_engine *engine, struct cl_scan_options *scanoptions);
      |                                         ~~~~~~~~~~~~^~~~~~~~
ClamAV.xs:219:40: warning: passing argument 3 of ‘cl_scandesc’ from incompatible pointer type [-Wincompatible-pointer-types]
  219 |     status = cl_scandesc(fd, &virname, &scanned, c->root, options);
      |                                        ^~~~~~~~
      |                                        |
      |                                        long unsigned int *
In file included from ClamAV.xs:11:
/usr/include/clamav.h:894:76: note: expected ‘const char **’ but argument is of type ‘long unsigned int *’
  894 | extern cl_error_t cl_scandesc(int desc, const char *filename, const char **virname, unsigned long int *scanned, const struct cl_engine *engine, struct cl_scan_options *scanoptions);
      |                                                               ~~~~~~~~~~~~~^~~~~~~
ClamAV.xs:219:51: warning: passing argument 4 of ‘cl_scandesc’ from incompatible pointer type [-Wincompatible-pointer-types]
  219 |     status = cl_scandesc(fd, &virname, &scanned, c->root, options);
      |                                                  ~^~~~~~
      |                                                   |
      |                                                   struct cl_engine *
In file included from ClamAV.xs:11:
/usr/include/clamav.h:894:104: note: expected ‘long unsigned int *’ but argument is of type ‘struct cl_engine *’
  894 | extern cl_error_t cl_scandesc(int desc, const char *filename, const char **virname, unsigned long int *scanned, const struct cl_engine *engine, struct cl_scan_options *scanoptions);
      |                                                                                     ~~~~~~~~~~~~~~~~~~~^~~~~~~
ClamAV.xs:219:59: warning: passing argument 5 of ‘cl_scandesc’ makes pointer from integer without a cast [-Wint-conversion]
  219 |     status = cl_scandesc(fd, &virname, &scanned, c->root, options);
      |                                                           ^~~~~~~
      |                                                           |
      |                                                           int
In file included from ClamAV.xs:11:
/usr/include/clamav.h:894:137: note: expected ‘const struct cl_engine *’ but argument is of type ‘int’
  894 | _scandesc(int desc, const char *filename, const char **virname, unsigned long int *scanned, const struct cl_engine *engine, struct cl_scan_options *scanoptions);
      |                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~

ClamAV.xs:219:14: error: too few arguments to function ‘cl_scandesc’
  219 |     status = cl_scandesc(fd, &virname, &scanned, c->root, options);
      |              ^~~~~~~~~~~
In file included from ClamAV.xs:11:
/usr/include/clamav.h:894:19: note: declared here
  894 | extern cl_error_t cl_scandesc(int desc, const char *filename, const char **virname, unsigned long int *scanned, const struct cl_engine *engine, struct cl_scan_options *scanoptions);
      |                   ^~~~~~~~~~~
ClamAV.xs: In function ‘clamav_perl__scanfile’:
ClamAV.xs:259:54: warning: passing argument 5 of ‘cl_scanfile’ makes pointer from integer without a cast [-Wint-conversion]
  259 |     status = cl_scanfile(p, &msg, &scanned, c->root, options);
      |                                                      ^~~~~~~
      |                                                      |
      |                                                      int
In file included from ClamAV.xs:11:
/usr/include/clamav.h:922:159: note: expected ‘struct cl_scan_options *’ but argument is of type ‘int’
  922 | har *filename, const char **virname, unsigned long int *scanned, const struct cl_engine *engine, struct cl_scan_options *scanoptions);
      |                                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~

ClamAV.xs: In function ‘clamav_perl_constant’:
ClamAV.xs:352:44: error: ‘CL_SCAN_RAW’ undeclared (first use in this function)
  352 |     if (strEQ("CL_SCAN_RAW", name)) return CL_SCAN_RAW;
      |                                            ^~~~~~~~~~~
ClamAV.xs:352:44: note: each undeclared identifier is reported only once for each function it appears in
ClamAV.xs:353:48: error: ‘CL_SCAN_ARCHIVE’ undeclared (first use in this function); did you mean ‘CL_SCAN_PARSE_PE’?
  353 |     if (strEQ("CL_SCAN_ARCHIVE", name)) return CL_SCAN_ARCHIVE;
      |                                                ^~~~~~~~~~~~~~~
      |                                                CL_SCAN_PARSE_PE
ClamAV.xs:354:45: error: ‘CL_SCAN_MAIL’ undeclared (first use in this function)
  354 |     if (strEQ("CL_SCAN_MAIL", name)) return CL_SCAN_MAIL;
      |                                             ^~~~~~~~~~~~
ClamAV.xs:355:45: error: ‘CL_SCAN_OLE2’ undeclared (first use in this function)
  355 |     if (strEQ("CL_SCAN_OLE2", name)) return CL_SCAN_OLE2;
      |                                             ^~~~~~~~~~~~
ClamAV.xs:356:55: error: ‘CL_SCAN_BLOCKENCRYPTED’ undeclared (first use in this function)
  356 |     if (strEQ("CL_SCAN_BLOCKENCRYPTED", name)) return CL_SCAN_BLOCKENCRYPTED;
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~
ClamAV.xs:357:45: error: ‘CL_SCAN_HTML’ undeclared (first use in this function)
  357 |     if (strEQ("CL_SCAN_HTML", name)) return CL_SCAN_HTML;
      |                                             ^~~~~~~~~~~~
ClamAV.xs:358:43: error: ‘CL_SCAN_PE’ undeclared (first use in this function)
  358 |     if (strEQ("CL_SCAN_PE", name)) return CL_SCAN_PE;
      |                                           ^~~~~~~~~~
ClamAV.xs:359:52: error: ‘CL_SCAN_BLOCKBROKEN’ undeclared (first use in this function)
  359 |     if (strEQ("CL_SCAN_BLOCKBROKEN", name)) return CL_SCAN_BLOCKBROKEN;
      |                                                    ^~~~~~~~~~~~~~~~~~~
ClamAV.xs:360:48: error: ‘CL_SCAN_MAILURL’ undeclared (first use in this function)
  360 |     if (strEQ("CL_SCAN_MAILURL", name)) return CL_SCAN_MAILURL;
      |                                                ^~~~~~~~~~~~~~~
ClamAV.xs:361:49: error: ‘CL_SCAN_BLOCKMAX’ undeclared (first use in this function)
  361 |     if (strEQ("CL_SCAN_BLOCKMAX", name)) return CL_SCAN_BLOCKMAX;
      |                                                 ^~~~~~~~~~~~~~~~
ClamAV.xs:362:52: error: ‘CL_SCAN_ALGORITHMIC’ undeclared (first use in this function)
  362 |     if (strEQ("CL_SCAN_ALGORITHMIC", name)) return CL_SCAN_ALGORITHMIC;
      |                                                    ^~~~~~~~~~~~~~~~~~~
ClamAV.xs:363:58: error: ‘CL_SCAN_PHISHING_BLOCKSSL’ undeclared (first use in this function)
  363 |     if (strEQ("CL_SCAN_PHISHING_BLOCKSSL", name)) return CL_SCAN_PHISHING_BLOCKSSL;
      |                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~
ClamAV.xs:364:60: error: ‘CL_SCAN_PHISHING_BLOCKCLOAK’ undeclared (first use in this function)
  364 |     if (strEQ("CL_SCAN_PHISHING_BLOCKCLOAK", name)) return CL_SCAN_PHISHING_BLOCKCLOAK;
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
ClamAV.xs:365:44: error: ‘CL_SCAN_ELF’ undeclared (first use in this function)
  365 |     if (strEQ("CL_SCAN_ELF", name)) return CL_SCAN_ELF;
      |                                            ^~~~~~~~~~~
ClamAV.xs:366:44: error: ‘CL_SCAN_PDF’ undeclared (first use in this function)
  366 |     if (strEQ("CL_SCAN_PDF", name)) return CL_SCAN_PDF;
      |                                            ^~~~~~~~~~~
ClamAV.xs:367:51: error: ‘CL_SCAN_STRUCTURED’ undeclared (first use in this function)
  367 |     if (strEQ("CL_SCAN_STRUCTURED", name)) return CL_SCAN_STRUCTURED;
      |                                                   ^~~~~~~~~~~~~~~~~~
ClamAV.xs:368:62: error: ‘CL_SCAN_STRUCTURED_SSN_NORMAL’ undeclared (first use in this function); did you mean ‘CL_SCAN_HEURISTIC_STRUCTURED_SSN_NORMAL’?
  368 |     if (strEQ("CL_SCAN_STRUCTURED_SSN_NORMAL", name)) return CL_SCAN_STRUCTURED_SSN_NORMAL;
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                              CL_SCAN_HEURISTIC_STRUCTURED_SSN_NORMAL
ClamAV.xs:369:64: error: ‘CL_SCAN_STRUCTURED_SSN_STRIPPED’ undeclared (first use in this function); did you mean ‘CL_SCAN_HEURISTIC_STRUCTURED_SSN_STRIPPED’?
  369 |     if (strEQ("CL_SCAN_STRUCTURED_SSN_STRIPPED", name)) return CL_SCAN_STRUCTURED_SSN_STRIPPED;
      |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                CL_SCAN_HEURISTIC_STRUCTURED_SSN_STRIPPED
ClamAV.xs:370:56: error: ‘CL_SCAN_PARTIAL_MESSAGE’ undeclared (first use in this function); did you mean ‘CL_SCAN_MAIL_PARTIAL_MESSAGE’?
  370 |     if (strEQ("CL_SCAN_PARTIAL_MESSAGE", name)) return CL_SCAN_PARTIAL_MESSAGE;
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~
      |                                                        CL_SCAN_MAIL_PARTIAL_MESSAGE
ClamAV.xs:371:61: error: ‘CL_SCAN_HEURISTIC_PRECEDENCE’ undeclared (first use in this function); did you mean ‘CL_SCAN_HEURISTIC_BROKEN’?
  371 |     if (strEQ("CL_SCAN_HEURISTIC_PRECEDENCE", name)) return CL_SCAN_HEURISTIC_PRECEDENCE;
      |                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                             CL_SCAN_HEURISTIC_BROKEN
ClamAV.xs:393:47: error: ‘CL_SCAN_STDOPT’ undeclared (first use in this function); did you mean ‘CL_DB_STDOPT’?
  393 |     if (strEQ("CL_SCAN_STDOPT", name)) return CL_SCAN_STDOPT;
      |                                               ^~~~~~~~~~~~~~
      |                                               CL_DB_STDOPT
make[1]: *** [Makefile:335: ClamAV.o] Error 1
make[1]: Leaving directory '/root/.cpan/build/Mail-ClamAV-0.30-0/_Inline/build/Mail/ClamAV'

A problem was encountered while attempting to compile and install your Inline
C code. The command that failed was:
  "make" with error code 2

The build directory was:
/root/.cpan/build/Mail-ClamAV-0.30-0/_Inline/build/Mail/ClamAV

To debug the problem, cd to the build directory, and inspect the output files.

 at /root/.cpan/build/Mail-ClamAV-0.30-0/blib/lib/Mail/ClamAV.pm line 162.
	...propagated at /usr/share/perl5/Inline/C.pm line 888.
BEGIN failed--compilation aborted at /root/.cpan/build/Mail-ClamAV-0.30-0/blib/lib/Mail/ClamAV.pm line 162.
Compilation failed in require.
BEGIN failed--compilation aborted.
make: *** [Makefile:824: ClamAV.inl] Error 25
  CAVAC/Mail-ClamAV-0.30.tar.gz
  /usr/bin/make -- NOT OK

Can someone please tell me what I did wrong?

Sincerely,
Ulrich Frey.

**Comment by KHIT93** [comment]
Hi
Thank you for reaching out.
There is a currently a minor issue with the encryption key generated during installation, which relates to the first issue. We are working on fixing this

In terms of ClamAV compilation, it must be related to an underlying issue with perhaps a package that has recently updated. I will have to due a few tests on a 20.04 system to see if it can be reproduced.

**Comment by shawniverson** [comment]
Mail::ClamAV module has a bug.  Here's a patch that needs applied to the MakeFile prior to compilation:

https://github.com/MailScanner/v5/blob/6e2413729eec860fee3ba0279def6259f030b3e4/debian/patch/patch.diff

**Comment by shawniverson** [comment]
Looks resolved via exclusion of module in commit 220af7082863daca7ba71624ec81987cc03ae8d5

**Comment by KHIT93** [comment]
Issue with Mail::ClamAV is resolved.
Interpolation issue during execution of script is also handled, so if you reinstall the server and run the installation again, it should now work

**Comment by freyuh** [comment]
Okay, thanks.
I'll give it a try and report back.

**Comment by freyuh** [comment]
Sorry, but it stops with the next error:

Configure MailScanner...
Traceback (most recent call last):
  File "./installer/mailscanner.py", line 11, in <module>
    from installer.mailguardian import SYSTEMCTL_BIN
ModuleNotFoundError: No module named 'installer'
We are really sorry, but something seems to have gone wrong or the script was aborted

**Comment by KHIT93** [comment]
Thank you for reporting back.
In the specific file that line was removed from the code, so it seems like you are somehow running on the old code.
If you have not reinstalled your server, there is a chance that some parts of the process is skipped, such as downloading the latest sourcecode for the installation scripts.
Please ensure that your server is completely reinstalled as a fresh Ubuntu 20.04.3 LTS and then redownload the installation script

**Comment by freyuh** [comment]
Ok, yes you are right. I didn't reinstall the OS. I thought, that the script would updater all necessary files/scripts.
I will install from scratch ...

**Comment by freyuh** [comment]
Now the installation went through with only one warning(?) at the end:

Filename Checks: Windows/DOS Executable (1 eicar.com)
Other Checks: Found 1 problems
Virus and Content Scanning: Starting
Clamd::ERROR:: UNKNOWN CLAMD RETURN ./File path check failure: Permission denied. ERROR :: /var/spool/MailScanner/incoming/56639
Virus Scanning: Clamd found 1 infections
Virus Scanning: Found 1 viruses

**Comment by shawniverson** [comment]
I think clamav user needs to be a member of the mtagroup possibly.

**Comment by freyuh** [comment]
It is a member of the group.
but when doing a 'ls' on the folder /var/spool/MailScanner/incoming there is no folder 56639.

**Comment by shawniverson** [comment]
Yeah the folder only exists for the duration of the scan. What are the current owner/permissions on /var/spool/MailScanner/incoming?

**Comment by shawniverson** [comment]
Silly question, did you reboot after install? I noticed I got that initially but after the restart it was gone when I ran `MailScanner --lint`

**Comment by freyuh** [comment]
Yes I rebooted, but didn't do another scan afterwards.
drwxrwx--- 9 postfix mtagroup 4096 Nov 26 11:23 incoming/, so mtagroup and therefore clamav should have no problems writing files.
Now did the scan and got no error ...

**Comment by freyuh** [comment]
So I close this issue now.
