### ISSUE TITLE
MailGuardian for inclusion in eFa

### ISSUE THREAD

**Issue by shawniverson** [KHIT93/mailguardian#84]
Greetings!

I have followed this project for a while and would like to inquire about including MailGuardian as a frontend to eFa.

I find the interface to be clean and well-defined, and it provides functionality beyond the traditional MailWatch interface.

**Comment by KHIT93** [comment]
Hi
Thank you for reaching out. I have also previously done some exploration of eFa and the state of the MailWatch UI in eFa was actually one of the reasons for starting the MailGuardian project.
Feel free to include MailGuardian in eFa and let me know if there are any issues that need to be fixed along the way

**Comment by shawniverson** [comment]
That is great news. I will add this and let you know of any issues and/or fixes.
